// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/github/byakkili/bim/core/protobuf/Packet.proto

package com.github.byakkili.bim.core.protobuf;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * Protobuf enum {@code MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TEXT = 0;</code>
     */
    TEXT(0),
    /**
     * <code>IMAGE = 1;</code>
     */
    IMAGE(1),
    /**
     * <code>VOICE = 2;</code>
     */
    VOICE(2),
    /**
     * <code>VIDEO = 3;</code>
     */
    VIDEO(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TEXT = 0;</code>
     */
    public static final int TEXT_VALUE = 0;
    /**
     * <code>IMAGE = 1;</code>
     */
    public static final int IMAGE_VALUE = 1;
    /**
     * <code>VOICE = 2;</code>
     */
    public static final int VOICE_VALUE = 2;
    /**
     * <code>VIDEO = 3;</code>
     */
    public static final int VIDEO_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgType forNumber(int value) {
      switch (value) {
        case 0: return TEXT;
        case 1: return IMAGE;
        case 2: return VOICE;
        case 3: return VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.byakkili.bim.core.protobuf.Packet.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgType)
  }

  /**
   * <pre>
   * 聊天类型
   * </pre>
   *
   * Protobuf enum {@code ChatType}
   */
  public enum ChatType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PRIVATE = 0;</code>
     */
    PRIVATE(0),
    /**
     * <code>GROUP = 1;</code>
     */
    GROUP(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PRIVATE = 0;</code>
     */
    public static final int PRIVATE_VALUE = 0;
    /**
     * <code>GROUP = 1;</code>
     */
    public static final int GROUP_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChatType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ChatType forNumber(int value) {
      switch (value) {
        case 0: return PRIVATE;
        case 1: return GROUP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChatType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
            public ChatType findValueByNumber(int number) {
              return ChatType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.byakkili.bim.core.protobuf.Packet.getDescriptor().getEnumTypes().get(1);
    }

    private static final ChatType[] VALUES = values();

    public static ChatType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChatType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ChatType)
  }

  /**
   * <pre>
   * Command
   * </pre>
   *
   * Protobuf enum {@code Command}
   */
  public enum Command
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHAT = 0;</code>
     */
    CHAT(0),
    /**
     * <code>CHAT_ACK = 1;</code>
     */
    CHAT_ACK(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CHAT = 0;</code>
     */
    public static final int CHAT_VALUE = 0;
    /**
     * <code>CHAT_ACK = 1;</code>
     */
    public static final int CHAT_ACK_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Command valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Command forNumber(int value) {
      switch (value) {
        case 0: return CHAT;
        case 1: return CHAT_ACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Command>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Command> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Command>() {
            public Command findValueByNumber(int number) {
              return Command.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.byakkili.bim.core.protobuf.Packet.getDescriptor().getEnumTypes().get(2);
    }

    private static final Command[] VALUES = values();

    public static Command valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Command)
  }

  public interface ChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Chat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 序列号
     * </pre>
     *
     * <code>int64 seq = 1;</code>
     * @return The seq.
     */
    long getSeq();

    /**
     * <code>string to = 2;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.Command cmd = 4;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    int getCmdValue();
    /**
     * <code>.Command cmd = 4;</code>
     * @return The cmd.
     */
    com.github.byakkili.bim.core.protobuf.Packet.Command getCmd();

    /**
     * <code>.MsgType msgType = 5;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.MsgType msgType = 5;</code>
     * @return The msgType.
     */
    com.github.byakkili.bim.core.protobuf.Packet.MsgType getMsgType();

    /**
     * <code>.ChatType chatType = 6;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    int getChatTypeValue();
    /**
     * <code>.ChatType chatType = 6;</code>
     * @return The chatType.
     */
    com.github.byakkili.bim.core.protobuf.Packet.ChatType getChatType();
  }
  /**
   * <pre>
   * 聊天
   * </pre>
   *
   * Protobuf type {@code Chat}
   */
  public  static final class Chat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Chat)
      ChatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Chat.newBuilder() to construct.
    private Chat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Chat() {
      to_ = "";
      content_ = "";
      cmd_ = 0;
      msgType_ = 0;
      chatType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Chat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Chat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              seq_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              chatType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.byakkili.bim.core.protobuf.Packet.internal_static_Chat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.byakkili.bim.core.protobuf.Packet.internal_static_Chat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.byakkili.bim.core.protobuf.Packet.Chat.class, com.github.byakkili.bim.core.protobuf.Packet.Chat.Builder.class);
    }

    public static final int SEQ_FIELD_NUMBER = 1;
    private long seq_;
    /**
     * <pre>
     * 序列号
     * </pre>
     *
     * <code>int64 seq = 1;</code>
     * @return The seq.
     */
    public long getSeq() {
      return seq_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private volatile java.lang.Object to_;
    /**
     * <code>string to = 2;</code>
     * @return The to.
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 4;
    private int cmd_;
    /**
     * <code>.Command cmd = 4;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.Command cmd = 4;</code>
     * @return The cmd.
     */
    public com.github.byakkili.bim.core.protobuf.Packet.Command getCmd() {
      @SuppressWarnings("deprecation")
      com.github.byakkili.bim.core.protobuf.Packet.Command result = com.github.byakkili.bim.core.protobuf.Packet.Command.valueOf(cmd_);
      return result == null ? com.github.byakkili.bim.core.protobuf.Packet.Command.UNRECOGNIZED : result;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 5;
    private int msgType_;
    /**
     * <code>.MsgType msgType = 5;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.MsgType msgType = 5;</code>
     * @return The msgType.
     */
    public com.github.byakkili.bim.core.protobuf.Packet.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      com.github.byakkili.bim.core.protobuf.Packet.MsgType result = com.github.byakkili.bim.core.protobuf.Packet.MsgType.valueOf(msgType_);
      return result == null ? com.github.byakkili.bim.core.protobuf.Packet.MsgType.UNRECOGNIZED : result;
    }

    public static final int CHATTYPE_FIELD_NUMBER = 6;
    private int chatType_;
    /**
     * <code>.ChatType chatType = 6;</code>
     * @return The enum numeric value on the wire for chatType.
     */
    public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <code>.ChatType chatType = 6;</code>
     * @return The chatType.
     */
    public com.github.byakkili.bim.core.protobuf.Packet.ChatType getChatType() {
      @SuppressWarnings("deprecation")
      com.github.byakkili.bim.core.protobuf.Packet.ChatType result = com.github.byakkili.bim.core.protobuf.Packet.ChatType.valueOf(chatType_);
      return result == null ? com.github.byakkili.bim.core.protobuf.Packet.ChatType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (seq_ != 0L) {
        output.writeInt64(1, seq_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (cmd_ != com.github.byakkili.bim.core.protobuf.Packet.Command.CHAT.getNumber()) {
        output.writeEnum(4, cmd_);
      }
      if (msgType_ != com.github.byakkili.bim.core.protobuf.Packet.MsgType.TEXT.getNumber()) {
        output.writeEnum(5, msgType_);
      }
      if (chatType_ != com.github.byakkili.bim.core.protobuf.Packet.ChatType.PRIVATE.getNumber()) {
        output.writeEnum(6, chatType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, seq_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (cmd_ != com.github.byakkili.bim.core.protobuf.Packet.Command.CHAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, cmd_);
      }
      if (msgType_ != com.github.byakkili.bim.core.protobuf.Packet.MsgType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgType_);
      }
      if (chatType_ != com.github.byakkili.bim.core.protobuf.Packet.ChatType.PRIVATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, chatType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.byakkili.bim.core.protobuf.Packet.Chat)) {
        return super.equals(obj);
      }
      com.github.byakkili.bim.core.protobuf.Packet.Chat other = (com.github.byakkili.bim.core.protobuf.Packet.Chat) obj;

      if (getSeq()
          != other.getSeq()) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (cmd_ != other.cmd_) return false;
      if (msgType_ != other.msgType_) return false;
      if (chatType_ != other.chatType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeq());
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + chatType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.byakkili.bim.core.protobuf.Packet.Chat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.byakkili.bim.core.protobuf.Packet.Chat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 聊天
     * </pre>
     *
     * Protobuf type {@code Chat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Chat)
        com.github.byakkili.bim.core.protobuf.Packet.ChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.byakkili.bim.core.protobuf.Packet.internal_static_Chat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.byakkili.bim.core.protobuf.Packet.internal_static_Chat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.byakkili.bim.core.protobuf.Packet.Chat.class, com.github.byakkili.bim.core.protobuf.Packet.Chat.Builder.class);
      }

      // Construct using com.github.byakkili.bim.core.protobuf.Packet.Chat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        seq_ = 0L;

        to_ = "";

        content_ = "";

        cmd_ = 0;

        msgType_ = 0;

        chatType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.byakkili.bim.core.protobuf.Packet.internal_static_Chat_descriptor;
      }

      @java.lang.Override
      public com.github.byakkili.bim.core.protobuf.Packet.Chat getDefaultInstanceForType() {
        return com.github.byakkili.bim.core.protobuf.Packet.Chat.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.byakkili.bim.core.protobuf.Packet.Chat build() {
        com.github.byakkili.bim.core.protobuf.Packet.Chat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.byakkili.bim.core.protobuf.Packet.Chat buildPartial() {
        com.github.byakkili.bim.core.protobuf.Packet.Chat result = new com.github.byakkili.bim.core.protobuf.Packet.Chat(this);
        result.seq_ = seq_;
        result.to_ = to_;
        result.content_ = content_;
        result.cmd_ = cmd_;
        result.msgType_ = msgType_;
        result.chatType_ = chatType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.byakkili.bim.core.protobuf.Packet.Chat) {
          return mergeFrom((com.github.byakkili.bim.core.protobuf.Packet.Chat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.byakkili.bim.core.protobuf.Packet.Chat other) {
        if (other == com.github.byakkili.bim.core.protobuf.Packet.Chat.getDefaultInstance()) return this;
        if (other.getSeq() != 0L) {
          setSeq(other.getSeq());
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.chatType_ != 0) {
          setChatTypeValue(other.getChatTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.byakkili.bim.core.protobuf.Packet.Chat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.byakkili.bim.core.protobuf.Packet.Chat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long seq_ ;
      /**
       * <pre>
       * 序列号
       * </pre>
       *
       * <code>int64 seq = 1;</code>
       * @return The seq.
       */
      public long getSeq() {
        return seq_;
      }
      /**
       * <pre>
       * 序列号
       * </pre>
       *
       * <code>int64 seq = 1;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(long value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 序列号
       * </pre>
       *
       * <code>int64 seq = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {
        
        seq_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>string to = 2;</code>
       * @return The to.
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to = 2;</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>string to = 2;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.Command cmd = 4;</code>
       * @return The enum numeric value on the wire for cmd.
       */
      public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.Command cmd = 4;</code>
       * @param value The enum numeric value on the wire for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdValue(int value) {
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Command cmd = 4;</code>
       * @return The cmd.
       */
      public com.github.byakkili.bim.core.protobuf.Packet.Command getCmd() {
        @SuppressWarnings("deprecation")
        com.github.byakkili.bim.core.protobuf.Packet.Command result = com.github.byakkili.bim.core.protobuf.Packet.Command.valueOf(cmd_);
        return result == null ? com.github.byakkili.bim.core.protobuf.Packet.Command.UNRECOGNIZED : result;
      }
      /**
       * <code>.Command cmd = 4;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.github.byakkili.bim.core.protobuf.Packet.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Command cmd = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.MsgType msgType = 5;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.MsgType msgType = 5;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MsgType msgType = 5;</code>
       * @return The msgType.
       */
      public com.github.byakkili.bim.core.protobuf.Packet.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        com.github.byakkili.bim.core.protobuf.Packet.MsgType result = com.github.byakkili.bim.core.protobuf.Packet.MsgType.valueOf(msgType_);
        return result == null ? com.github.byakkili.bim.core.protobuf.Packet.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MsgType msgType = 5;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(com.github.byakkili.bim.core.protobuf.Packet.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MsgType msgType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int chatType_ = 0;
      /**
       * <code>.ChatType chatType = 6;</code>
       * @return The enum numeric value on the wire for chatType.
       */
      public int getChatTypeValue() {
        return chatType_;
      }
      /**
       * <code>.ChatType chatType = 6;</code>
       * @param value The enum numeric value on the wire for chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatTypeValue(int value) {
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ChatType chatType = 6;</code>
       * @return The chatType.
       */
      public com.github.byakkili.bim.core.protobuf.Packet.ChatType getChatType() {
        @SuppressWarnings("deprecation")
        com.github.byakkili.bim.core.protobuf.Packet.ChatType result = com.github.byakkili.bim.core.protobuf.Packet.ChatType.valueOf(chatType_);
        return result == null ? com.github.byakkili.bim.core.protobuf.Packet.ChatType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ChatType chatType = 6;</code>
       * @param value The chatType to set.
       * @return This builder for chaining.
       */
      public Builder setChatType(com.github.byakkili.bim.core.protobuf.Packet.ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        chatType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ChatType chatType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Chat)
    }

    // @@protoc_insertion_point(class_scope:Chat)
    private static final com.github.byakkili.bim.core.protobuf.Packet.Chat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.byakkili.bim.core.protobuf.Packet.Chat();
    }

    public static com.github.byakkili.bim.core.protobuf.Packet.Chat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Chat>
        PARSER = new com.google.protobuf.AbstractParser<Chat>() {
      @java.lang.Override
      public Chat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Chat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Chat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Chat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.byakkili.bim.core.protobuf.Packet.Chat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2com/github/byakkili/bim/core/protobuf/" +
      "Packet.proto\"\177\n\004Chat\022\013\n\003seq\030\001 \001(\003\022\n\n\002to\030" +
      "\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\025\n\003cmd\030\004 \001(\0162\010.Co" +
      "mmand\022\031\n\007msgType\030\005 \001(\0162\010.MsgType\022\033\n\010chat" +
      "Type\030\006 \001(\0162\t.ChatType*4\n\007MsgType\022\010\n\004TEXT" +
      "\020\000\022\t\n\005IMAGE\020\001\022\t\n\005VOICE\020\002\022\t\n\005VIDEO\020\003*\"\n\010C" +
      "hatType\022\013\n\007PRIVATE\020\000\022\t\n\005GROUP\020\001*!\n\007Comma" +
      "nd\022\010\n\004CHAT\020\000\022\014\n\010CHAT_ACK\020\001B)\n%com.github" +
      ".byakkili.bim.core.protobufP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Chat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Chat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chat_descriptor,
        new java.lang.String[] { "Seq", "To", "Content", "Cmd", "MsgType", "ChatType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
